services:
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-image:latest
    container_name: my-container
    ports:
      - "80:8080"  # Map host port 8080 to container port 8080
    environment:
      - ENV_VAR=example  # Set environment variables
    volumes:
      - ./data:/app/data  # Mount host directory to container

# Uncomment if you want to add a volume or network definition
# volumes:
#   my-volume:
# networks:
#   my-network:
